### ISSUE TITLE
Inventory isnt working in PGA 1.16.4

### ISSUE THREAD

**Issue by me6669** [ArtixAllMighty/PublicGuiAnnouncement#6]
All other GUIs are visible when open, except inventory and creative inventory. I tried it on a instance without any other mods and nothing has changed. Do you see this bug too?

**Comment by me6669** [comment]
Nevermind! I set up a LAN and could now see it. I was looking at the GUIs using shoulder surfing reloaded mod and for some reason it didnt show ? Not sure but I figured it out now !

**Comment by AbsolemJackdaw** [comment]
If I'm not mistaking, for the player I got an exception for the inventory so it doesnt show up when the plaeyr is drawn in the gui. can't remember if its that or not. 
In Lan it would show up, because it's canceled rendering only for the player. 
But again, can't rememebr if that was a feature that I added and wether it was kept or removed since.
