### ISSUE TITLE
Broken on servers without the mod

### ISSUE THREAD

**Issue by RyanCR03** [ArtixAllMighty/PublicGuiAnnouncement#9]
server i tested: hypixel

**Comment by AbsolemJackdaw** [comment]
mod needs to be installed on both server and client. 
it is not mentioned this is a client only mod on the curseforge page or github.
thanks for understanding, 
Apologies for any inconvenience.

**Comment by RyanCR03** [comment]
i meant it doesnt let you connect to hypixel when using the mod client side

**Comment by AbsolemJackdaw** [comment]
normal ? mods need to match or you can't join a server. 
they need to match if the mod is required server side. which is the case here.

**Comment by RyanCR03** [comment]
but hypixel is not a modded server
this is the only mod that i have that sends me to limbo

**Comment by KiriCattus** [comment]
This is not a client side mod (A mod that is only used on the client that you use to play singleplayer or multiplayer) this mod is needed both on the server and the client to work properly, either play on a server that has this mod installed or ask them to install it (Highly unlikely since Hypixel has a strict list of mods you're actually alowed to use)
